common:
  host: localhost
  passwd: paranoia
  log: e:/tmp
  db: e:/tmp
  response_border: number of response border
  icon: http://img.tweetimag.es/i/mapserver2007

other:
  dummy_value: xxxxxxxxxx
  config: e:/tmp/config.yml
  dummy_url: http://xxxxxxxxxxxxxxxxxxxxxx/xxx.png
  timeout: 0.00000000001
