common:
  host: your host
  passwd: your growl password
  log: /path/to/log
  db: /path/to/dbfile
  response_border: number of response border
  icon: url or path

other:
  dummy_value: xxxxxxxxxx
  config: /path/to/config.yml
  dummy_url: http://xxxxxxxxxxxxxxxxxxxxxx/xxx.png
  timeout: 0.00000000001
